example.organization.property: "I AM THE DEFAULT ORGANIZATION SERVICE"

####

example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
#spring.datasource.initialization-mode: always
#spring.jpa.show-sql: "true"
#spring.jpa.hibernate.show-sql: true
#spring.jpa.generate-ddl: true
#spring.jpa.hibernate.ddl-auto: create
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/stock"
#spring.datasource.username: "postgres"
#spring.datasource.password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
#spring.datasource.url: "jdbc:postgresql://localhost:5432/eagle_eye_local"
spring.datasource.username: "dbexerphi_dba"
spring.datasource.password: "admin"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
#bug fix
#spring.cloud.refresh.enabled: false
#redis.server: "redis"
#redis.port: "6379"
#signing.key: "345345fsdfsf5345"
